name: RxUserDefaults
options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
targets:
  RxUserDefaults:
    type: framework
    platform: iOS
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: 10.3
      PRODUCT_BUNDLE_IDENTIFIER: "de.number42.RxUserDefaults"
    scheme:
      testTargets:
        - RxUserDefaults-Tests
    sources:
      - Sources
      - Supporting Files
      - path: Headers
        buildPhase: headers
        type: folder
        headerVisibility: public
    dependencies:
        - carthage: RxSwift
        - carthage: RxCocoa
  RxUserDefaults-Tests:
    type: bundle.unit-test
    platform: iOS
    scheme: {}
    sources:
      - Tests
    dependencies:
      - target: RxUserDefaults
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxTest
      - carthage: RxBlocking
  TestApp:
      type: application
      platform: iOS
      scheme: {}
      sources:
        - TestApp
      dependencies:
        - framework: RxUserDefaults
