name: RxUserDefaults

targets:
  RxUserDefaults:
    type: framework
    platform: iOS
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: 10.3
        SWIFT_VERSION: "5.0"
        PRODUCT_BUNDLE_IDENTIFIER: "de.number42.RxUserDefaults"
#    scheme:
#      testTargets:
#        - RxUserDefaults-Tests
    sources:
      - Sources
      - Supporting Files
      - path: Headers
        buildPhase: headers
        type: folder
        headerVisibility: public
#  RxUserDefaults-Tests:
#    type: bundle.unit-test
#    platform: iOS
#    settings:
#        base:
#          SWIFT_VERSION: "5.0"
#    scheme: {}
#    sources:
#      - Tests
#    dependencies:
#      - target: RxUserDefaults
#      - carthage: RxSwift
#      - carthage: RxCocoa
#      - carthage: RxTest
#      - carthage: RxBlocking
  TestApp:
      type: application
      platform: iOS
      scheme: {}
      settings:
          base:
            SWIFT_VERSION: "5.0"
      sources:
        - TestApp
      dependencies:
        - framework: RxUserDefaults
