name: CI

on: pull_request
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@master
      - name: XcodeGen
        run: ./xcodegen
      - name: Build and test
        run: |
          xcodebuild build -destination "name=iPhone 11 Pro" -scheme RxUserDefaults_iOS
        env:
         platform: iOS Simulator
         OS: 12.2
         name: iPhone X
